### ISSUE TITLE
aioredis.create_redis_pool和asyncio_redis.Pool.create有什么区别，都用一个库不行吗？

### ISSUE THREAD

**Issue by ghost** [imnisen/quick_sanic_demo#1]
# 设置一般缓存的redis pool
    redis_pool = await aioredis.create_redis_pool(address=(redis_config.get('host', '127.0.0.1'),
                                                  redis_config.get('port', 6379)),
                                                  db=redis_config.get('db', 1),
                                                  loop=loop)
    app.redis_pool = redis_pool

    # 设置session使用的redis pool
    redis_cache_pool = await asyncio_redis.Pool.create(host=redis_cache_config.get('host', '127.0.0.1'),
                                                       port=redis_cache_config.get('port', 6379),
                                                       poolsize=10,
                                                       db=redis_cache_config.get('db', 1),
                                                       loop=loop)
    app.redis_cache_pool = redis_cache_pool

**Comment by imnisen** [comment]
时间有点久了，如果我没有记错的话，当初这样做是因为"sanic_session"这个插件不支持"aioredis",只支持"asyncio_redis"。而出于某种原因(记不清了)"aioredis"比"asyncio_redis"要工作得好。所以这里集成了两个redis pool，算是一种折衷临时处理。

但后来sanic_session应该支持aioredis了。所以你可以就用一个试试。

参见当初sanic_seesion提的一个issue. 
https://github.com/xen/sanic_session/issues/25

**Comment by ghost** [comment]
> 时间有点久了，如果我没有记错的话，当初这样做是因为"sanic_session"这个插件不支持"aioredis",只支持"asyncio_redis"。而出于某种原因(记不清了)"aioredis"比"asyncio_redis"要工作得好。所以这里集成了两个redis pool，算是一种折衷临时处理。
> 
> 但后来sanic_session应该支持aioredis了。所以你可以就用一个试试。
> 
> 参见当初sanic_seesion提的一个issue.
> [xen/sanic_session#25](https://github.com/xen/sanic_session/issues/25)

十分感谢。
